workflows:
  wgs_std_viper:
    url: "https://github.com/marrip/wgs_std_viper.git"
    tag: "1.0.2"
  wgs_somatic_snp_viper:
    url: "https://github.com/marrip/wgs_somatic_snp_viper.git"
    tag: "main"
  wgs_somatic_cnv_sv_viper:
    url: "https://github.com/marrip/wgs_somatic_cnv_sv_viper.git"
    tag: "1.0.0"

samples: "samples.tsv"
units: "units.tsv"

reference:
  adapter:
    fwd: "TACACTCTTTCCCTACACGACGCTCTTCCGATCT"
    rev: "GTGACTGGAGTTCAGACGTGTGCTCTTCCGATCT"
  fasta: ""
  dct: ""
  intervals: ""
  loci: ""
  sites: ""

cnvkit:
  pon: ""

cnvnator:
  pon: ""

manta:
  pon: ""

tiddit:
  pon: ""

vardict:
  bed: ""

tools:
  cnvkit: "docker://marrip/cnvkit:0.9.7"
  cnvnator: "docker://marrip/cnvnator:0.4.1"
  common: "docker://marrip/common:1.1.0"
  cutadapt: "docker://marrip/cutadapt:3.3"
  fastqc: "docker://marrip/fastqc:0.11.9"
  gatk: "docker://broadinstitute/gatk:4.2.0.0"
  manta: "docker://marrip/manta:v1.6.0"
  mosdepth: "docker://marrip/mosdepth:v0.3.1"
  python: "docker://python:3.10-rc-slim-buster"
  tiddit: "docker://marrip/tiddit:2.12.1"
  vardict: "docker://marrip/vardict:1.8.2"
